export const TOKEN_MISSING = "TOKEN_MISSING";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";

export const SERVER_UNREACHABLE = "SERVER_UNREACHABLE";
export const NETWORK_DISCONNECT = "NETWORK_DISCONNECT";